<div class="row">
<section class="col-8">
    <h1>Articles</h1>
    <form class="searchbar">
        <label for="search">Rechercher un article :</label>
        <input type="text" id="search" name="search"/>
    </form>
    <div  id="article">
    <?php foreach ($articles as $article) : ?>
    <article class="row">
        <div class="col-3">
            <a href="article.php?id_article=<?=$article['ID_article']?>"><img class="miniature" src="img/<?=$article['image']?>"/></a>
        </div>
        <div class="col-9">
            <h2><?= $article['articleTitle'] ?></h2>
            <p><?= substr($article['articleText'], 0, 300); ?></p>
            <p><a class="btn btn-primary" href="article.php?id_article=<?=$article['ID_article']?>">En savoir plus</a></p>
            <p><em>Rédigé par <?= $article['authorFirstName'] ?> <?= $article['authorLastName'] ?>, le <?= $article['articleDate'] ?></em></p>
        </div>
    </article>
    <?php endforeach; ?>
    </div>
</section>
<aside class="col-4">
    <h1>Les derniers commentaires publiés :</h1>
    <div class="lastcomment" id="lastcomment">
    </div>
</aside>
</div>