<?php if (isset($_SESSION['admin'])) : ?>
    <?php if (isset($_GET['id_modif']) && $_GET['id_modif'] == 'article') : ?>
        <section>
            <h1>Editer un article</h1>
            <form action="modif_article.php" method="POST" enctype="multipart/form-data">
                <fieldset class="notflex"><legend><i class="fa-solid fa-file"></i> Article</legend>
                    <input type="hidden" name="id_modif" value="article"/>
                    <input id="id_article" name="id_article" type="hidden" value=<?=$id?>>
                    <input id="id_image" name="id_image" type="hidden" value=<?=$image?>>
                    <label for="title">Titre :</label>
                    <input class="adding" type="text" name="title" id="title" value=<?=$articleTitle?> />
                    <label for="article">Article :</label>
                    <textarea class="adding" name="article" id="article"><?=$articleText?></textarea>
                    <label for="image">Image :</label>
                    <input class="adding" type="file" id="image" name="image"/>
                    <label id="askdelete" for="delete">Voulez-vous supprimer l'image de l'article ?</label>
                    <input type="checkbox" id="delete" name="delete">
                    <select class="adding" name="author" id="author">
                        <?php foreach($authors as $author) : ?>
                            <?php if($authorSelected == $author['ID_author']) : ?>
                                <option value="<?= $author['ID_author'] ?>" selected><?= $author['authorFirstName']." ".$author['authorLastName'] ?></option>
                            <?php else : ?>
                                <option value="<?= $author['ID_author'] ?>"><?= $author['authorFirstName']." ".$author['authorLastName'] ?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </select>
                    <label for="categorie">categorie</label>
                    <select class="adding" name="categorie" id="categorie">
                        <?php foreach($categories as $categorie) : ?>
                            <?php if ($categorieSelected == $categorie['ID_categorie']) : ?>
                                <option value="<?= $categorie['ID_categorie'] ?>" selected><?= $categorie['categorieName'] ?></option>
                            <?php else : ?>
                                <option value="<?= $categorie['ID_categorie'] ?>"><?= $categorie['categorieName'] ?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </select>
                    <div class="button-mid"><button type="submit" class="button btn-valid">Mettre à jour</button></div>
                </fieldset>
            </form>
        </section>
    <?php elseif(isset($_GET['id_modif']) && $_GET['id_modif'] == 'auteur') : ?>
        <section>
            <h1>Editer un auteur</h1>
            <form action="modif_article.php" method="POST" enctype="multipart/form-data">
                <fieldset class="notflex"><legend><i class="fa-solid fa-file"></i> Auteur</legend>
                    <input type="hidden" name="id_modif" value="auteur"/>
                    <input type="hidden" name="id_author" value="<?=$id?>"/>
                    <label for="authorFirstName">Prénom :</label>
                    <input class="adding" type="text" name="authorFirstName" id="authorFirstName" value=<?=$authorfirstname?> />
                    <label for="authorLastName">Nom de famille :</label>
                    <input class="adding" type="text" name="authorLastName" id="authorLastName" value=<?=$authorlastname?> />
                    <div class="button-mid"><button type="submit" class="button btn-valid">Mettre à jour</button></div>
                </fieldset>
            </form>
        </section>
    <?php elseif(isset($_GET['id_modif']) && $_GET['id_modif'] == 'categorie') : ?>
        <section>
            <h1>Editer une catégorie</h1>
            <form action="modif_article.php" method="POST" enctype="multipart/form-data">
                <fieldset class="notflex"><legend><i class="fa-solid fa-file"></i> Catégorie</legend>
                    <input type="hidden" name="id_modif" value="categorie"/>
                    <input type="hidden" name="id_categorie" value="<?=$id?>"/>
                    <label for="categorieName">Nom de la catégorie :</label>
                    <input class="adding" type="text" name="categorieName" id="categorieName" value=<?=$categoriename?> />
                    <div class="button-mid"><button type="submit" class="button btn-valid">Mettre à jour</button></div>
                </fieldset>
            </form>
        </section>
    <?php endif; ?>
<?php else : ?>
    <?php header('location:admin.php'); ?>
<?php endif; ?>