<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Classic models order</title>
    <link rel="stylesheet" href="css/style.css" type="text/css" />
</head>
<body>
    <div class="container">
        <h1>Order form</h1>
        <article>
            <h2>Order list</h1>
            <table>
                <thead>
                    <tr>
                        <th>Order Number</th>
                        <th>Order Date</th>
                        <th>Shipped Date</th>
                        <th>Status</th>
                        <th>Customer</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($orders as $order) : ?>
                    <tr>
                        <td><a href="detail.php?id_order=<?=$order['orderNumber']?>"><?= $order["orderNumber"] ?></a></td>
                        <td><?= $order["orderDate"] ?></td>
                        <td><?= $order["shippedDate"] ?></td>
                        <td><?= $order["status"] ?></td>
                        <td><a href="detail_client.php?id_customer=<?=$order['customerNumber']?>"><?= $order["customerName"] ?></a></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </article>
    </div>
</body>
</html>