<?php if($this -> isAdmin()) : ?>
    <ul class="admin__menu">
        <li><a class="btn btn-admin" href="index.php?action=admin&content=dish">Add a new dish</a></li>
        <li><a class="btn btn-admin" href="index.php?action=admin&content=edit">Modify a dish</a></li>
        <li><a class="btn btn-admin" href="index.php?action=admin&content=reser">View all reservation</a></li>
        <li><a class="btn btn-admin" href="index.php?action=admin&content=command">View all commands</a></li>
    </ul>
<?php else : ?>
    <form action="index.php?action=admin" method="POST">
        <fieldset class="register__field"><Legend>Login admin</Legend>
            <label for="pseudo">Pseudo :</label>
            <input type="text" id="pseudo" name="pseudo"/>
            <label for="pass">Password :</label>
            <input type="password" id="pass" name="pass"/>
            <button type="submit">Log In !</button>
        </fieldset>
    </form>
<?php endif; ?>