<form action="index.php?action=login" method="POST">
    <fieldset class="register__field"><legend>Login information :</legend>
        <div class="row field__div">
            <label class="col-3" for="mail">Mail</label>
            <input class="col-9" type="mail" id="mail" name="mail"/>
            <label class="col-3" for="password">password</label>
            <input class="col-9" type="password" id="password" name="password"/>
        </div>
        <button class="field__btn" type="submit">Send</button>
    </fieldset>
</form>