<article>
    <div>
        <ul>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor in facilis adipisci provident voluptates. Assumenda, dolorum possimus dignissimos eum voluptate ipsa ratione tempora minima veritatis sit eveniet modi amet dolores.</li>
            <li>Tenetur, eligendi, quisquam voluptatum at voluptate repellendus consequuntur qui commodi nulla quis. Corporis, nostrum consequatur consequuntur temporibus reprehenderit vero id maxime minus perferendis. Ullam, ut, tempore delectus nihil ipsum animi.</li>
            <li>Doloremque, eaque quos perspiciatis tempora sit minus soluta laboriosam saepe! Voluptate, sapiente cum nobis aspernatur nostrum placeat magni. Ut nesciunt dolorem repudiandae incidunt tempora eos inventore autem nemo ab cumque.</li>
            <li>Assumenda, ea, autem tempora ab distinctio aut quidem nulla molestias unde asperiores consectetur quis ad! Dolores, a doloremque quo labore similique cumque accusamus facere officia natus voluptatum tempore dolor odio.</li>
            <li>Doloremque, quod, commodi, quia, beatae ad fugit saepe ipsam tenetur laborum voluptas deleniti et cupiditate numquam dolore minima natus inventore culpa optio eaque labore. Iure labore ab illo commodi et?</li>
            <li>Nisi quisquam enim praesentium neque accusantium modi unde ut incidunt harum repellat? Doloribus commodi fugit architecto rem iusto! Quo, voluptatum omnis ea libero officiis deleniti soluta repellendus ullam quaerat sed.</li>
            <li>Nobis, nulla, quis sint ullam sapiente fugiat tempore eius debitis obcaecati temporibus illo delectus impedit ducimus architecto animi deserunt ipsum eum quae omnis provident dolorem necessitatibus perferendis voluptates dolorum quod?</li>
        </ul>
    </div>
</article>