<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="css/common-v3.css" type="text/css"/>
    <link rel="stylesheet" href="css/style.css" type="text/css"/>
</head>
<body>
    <header class="header">
        <h1>Layout.phtml</h1>
        <nav>
            <ul>
                <li><a href="index.php">Layout</a></li>
                <li><a href="page2.php">Page 2</a></li>
            </ul>
        </nav>
    </header>
    <div class="container">
        <main>
            <?php require $template.".phtml" ?>
        </main>
    </div>
    <footer class="footer">
        <p><a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/"><img class="copy" alt="Propriété de la 3W Academy" src="https://3wa.fr/wp-content/themes/3wa2015/img/logos/big.png"></a></p>
	    <p>Ce matériel pédagogique est la propriété de la <a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/">3W Academy</a>. Cet exercice a été réalisé par <a href="Catherine Denos">Catherine Denos</a>.</p>
    </footer>
</body>
</html>