<section>
    <h2>section</h2>
    <article>
        <h3>article</h3>
        <div>
            contenu
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis, a!</p>
            <p>Dolorum, ut quibusdam cumque eveniet quae esse similique qui iste?</p>
            <p>Alias, dolorem accusantium magnam quas eum delectus deleniti animi sit.</p>
            <p>Odio, quis officiis assumenda adipisci animi tenetur sit mollitia voluptatem!</p>
            <p>Odio, mollitia ea accusantium officiis aut eum quis soluta deserunt.</p>
            <p>Cum, quia, veritatis aspernatur maxime voluptatem sapiente aliquam voluptate natus.</p>
            <p>Omnis, adipisci, tempore! Natus, debitis, molestias id cupiditate ab iure.</p>
            <p>Provident, dolorem reiciendis officiis minus magnam at porro illum doloribus.</p>
            <p>Laboriosam sunt culpa quas dignissimos repellat. Voluptate libero ipsum dolorum.</p>
            <p>Dolores doloribus debitis harum repudiandae maxime possimus eligendi! Sit, quisquam.</p>
        </div>
    </article>
</section>