<section>
    <h1><i class="fa-solid fa-cart-shopping"></i> Make an order</h1>
    <form action="index.php?action=order" method="POST">
        <fieldset class="register__field"><legend>Add a dish :</legend>
            <label for="choice">Product :</label>
            <select name="choice" id="choice">
                <option value="z">Please choose a dish.</option>
                <?php foreach ($listdishs as $listdish) : ?>
                    <option value="<?=$listdish['ID_dish']?>"><?=$listdish['dishName']?></option>
                <?php endforeach; ?>
            </select>
            <div id="afficheur">
                
            </div>
            <div>
                <label for="quantity">Quantity :</label>
                <input type="number" id="quantity" min="1" max="10" name="quantity"/>
            </div>
            <button type='submit' class="btn btn-success" id="adding">Add to cart</button>
        </fieldset>
    </form>
    <form action="index.php?action=order" method="POST">
        <fieldset class="register__field"><legend>Your cart</legend>
            <table id="basket">
                
            </table>
            <button type="submit" class="btn btn-success" id="validate">Place order</button>
            <button type="button" class="btn btn-danger" id="emptyIt">Empty the cart</button>
        </fieldset>
    </form>
</section>